format_version: 10
environments:
  dev_env:
    pipelines:
      - publish-nuget
      - build-common
pipelines:
  build-common:
    environment_variables:
      ENV_VAR: "{{SECRET:[MyHomeSecrets][NUGET_APIKEY]}}"
    group: build-common-group
    label_template: "${commongit[:8]}"
    materials:
      commongit:
        git: https://github.com/alexIzual/gocd-nuget-test.git
        branch: master
        whitelist:
          - My.Common/**/*.*
          - /*.yaml
    stages:
      - unit_tests:
          jobs: 
            unit_tests:
              tasks:
                - exec:
                    working_directory: My.Common/
                    command: dotnet
                    arguments:
                      - test
                      - -v
                      - normal
      - build:
          clean_workspace: true
          jobs:
            build:
              tasks:
                - exec:
                    working_directory: My.Common/
                    command: dotnet
                    arguments:
                      - restore
                      - --verbosity
                      - quiet
                - exec:
                    working_directory: My.Common/
                    command: dotnet
                    arguments:
                      - build
                      - --configuration
                      - Release
                      - --verbosity
                      - quiet
                      - --no-restore
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - "suff=`date '+%Y%m%d%H%M%S'`; for proj in $(git diff HEAD^ HEAD --name-only *.csproj); do dotnet pack $proj --configuration Release --no-build --output './packages' --version-suffix 'Beta$suff'; done; echo 'Beta$suff'"
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - echo $ENV_VAR
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - '[ -d "/packages" ] && cd ''packages''; for pkg in $(echo *.nupkg); do dotnet nuget push $pkg --source ''Package source 1''; done'
  publish-nuget:
    group: deploy-common-group
    label_template: "${commongit[:8]}"
    locking: off
    materials:
      commongit:
        git: https://github.com/alexIzual/gocd-nuget-test.git
        branch: master
        whitelist:
          - My.Common/**/*.*
          - /*.yaml
      upstream:
        pipeline: build-common
        stage: unit_tests
    stages:
      - build:
          approval: manual
          clean_workspace: true
          jobs:
            publish:
              tasks:
                - exec:
                    command: dotnet
                    working_directory: My.Common/
                    arguments:
                      - "publish -c Release"
